name: ci

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:

  test:
    container: cariad/ci:1.4.0
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - id: cache-venv
        uses: actions/cache@v1
        with:
          key: ${{ runner.os }}-venv-${{ hashFiles('Pipfile.lock') }}
          path: ~/.local/share/virtualenvs

      - if: steps.cache-venv.outputs.cache-hit != 'true'
        run: pipenv sync --dev

      - run: pipenv run ./test.sh

  publish:
    needs:
      - test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - id: buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.ref }}
          restore-keys: buildx-

      - id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: cariad/web-ci

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
          labels: ${{ steps.docker_meta.outputs.labels }}
          pull: true
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
